name: evosync
description: Ein neues Flutter-Projekt.

# Die folgende Zeile verhindert, dass das Paket versehentlich
# mit `flutter pub publish` auf pub.dev veröffentlicht wird. 
# Dies ist für private Pakete bevorzugt.
publish_to: 'none' # Entfernen Sie diese Zeile, wenn Sie auf pub.dev veröffentlichen möchten.

# Versionsnummer und Build-Nummer für die Anwendung
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Speichern von Benutzereinstellungen, z.B. Dark Mode
  shared_preferences: ^2.3.2
  
  # Arbeiten mit Datums- und Zeitformaten
  intl: ^0.19.0
  
  # Darstellung von animierten Vektorgrafiken
  lottie: ^3.1.2

  # Verwaltung des globalen Zustands, z.B. Dark Mode
  provider: ^6.0.0

  # Animationen in Flutter
  animations: ^2.0.0

  # Cupertino Icons für iOS-Stil-Symbole
  cupertino_icons: ^1.0.2

  # Schritte vom Smartphone verwenden 
  pedometer: ^4.0.2

  # Verwaltung von Berechtigungen
  permission_handler: ^10.0.0

  # SQLite für die lokale Datenbankverwaltung
  sqflite: ^2.0.0
  
  # Pfadmanagement, um Dateipfade plattformübergreifend zu handhaben
  path: ^1.8.0
  
  # Pfad-Provider, um Verzeichnisse wie das Dokumentenverzeichnis zu finden
  path_provider: ^2.0.0

  # Um Svg Dateien zu verwenden
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Empfohlene Lints für gute Codierpraktiken
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets in der Anwendung
  assets:
    - assets/database/Index_exercises.json
    - assets/database/exercises/
    - assets/database/sportarten_met.json
    - assets/database/training_volumes.json
    - assets/database/fragenkatalog_experience.json
    - assets/database/Splits_Default.json
    - assets/images/male_backside.svg
    - assets/images/male_frontside.svg
    - assets/images/female_backside.svg
    - assets/images/female_frontside.svg
    - assets/database/body_svg_ids.json
    - assets/database/focus_presets.json

  # Weitere Informationen zum Hinzufügen von Assets aus Paketabhängigkeiten findest du unter
  # https://flutter.dev/assets-and-images/#from-packages
